name: Doxygen Consistency Check
on: [push, pull_request]
jobs:
  doxygen-completeness-check:
    name: Doxygen completeness check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run doxygen for C++ programs.
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
          working-directory: 'src'
          doxyfile-path: 'doxygen.cfg'